// `freeq.at/act` signing for the NPC agents (plain ESM — the agents run under
// bare node, not vite-node, so they can't import the TypeScript module).
//
// This is a second implementation of the same canonical as shared/src/act.ts.
// Duplicated crypto is a smell, so both are held to the SAME fixtures — the
// vectors generated by the Rust implementation — in shared/src/act.test.ts.
// If these two ever drift, that test fails.

import nacl from 'tweetnacl'
import { createHash } from 'node:crypto'

export const ACT_SIG_TAG = '+freeq.at/sig'

const strip = (name) => name.replace(/^\+?freeq\.at\//, '')
const covered = (n) => n === 'act' || n.startsWith('act-')
const b64url = (bytes) => Buffer.from(bytes).toString('base64url')

/** Exact bytes an act signature covers: JCS over the covered tags, keys
 *  stripped of the vendor prefix and sorted. */
export function actCanonical(tags) {
  const fields = {}
  for (const [name, value] of Object.entries(tags)) {
    const key = strip(name)
    if (covered(key)) fields[key] = value
  }
  return `{${Object.keys(fields)
    .sort()
    .map((k) => `${JSON.stringify(k)}:${JSON.stringify(fields[k])}`)
    .join(',')}}`
}

/** base64url-nopad(sha256(raw ed25519 public key)[0..16]) */
export function actKid(publicKey) {
  return b64url(createHash('sha256').update(Buffer.from(publicKey)).digest().subarray(0, 16))
}

/** `ed25519:<kid>:<base64url signature>` over the canonical bytes. */
export function signAct(tags, secretKey, publicKey) {
  const sig = nacl.sign.detached(new TextEncoder().encode(actCanonical(tags)), secretKey)
  return `ed25519:${actKid(publicKey)}:${b64url(sig)}`
}

/** Crockford base32 ULID: 48-bit time + 80-bit randomness, lexicographically
 *  sortable — the act-id the RFC correlates actions by. */
export function ulid(now = Date.now()) {
  const C = '0123456789ABCDEFGHJKMNPQRSTVWXYZ'
  let time = ''
  let t = now
  for (let i = 0; i < 10; i++) {
    time = C[t % 32] + time
    t = Math.floor(t / 32)
  }
  let rand = ''
  for (let i = 0; i < 16; i++) rand += C[Math.floor(Math.random() * 32)]
  return time + rand
}

/** Tag set for an action. Omit `to` for an open/claimable one — unassigned is
 *  the natural encoding of unassigned, and the channel it lands in is the queue. */
export function actTags({ kind, verb, id, from, title, to, caps, deadline, ctxHash, ref }) {
  const t = {
    '+freeq.at/act': kind,
    '+freeq.at/act-verb': verb,
    '+freeq.at/act-id': id,
    '+freeq.at/act-from': from,
  }
  if (title) t['+freeq.at/act-title'] = title
  if (to) t['+freeq.at/act-to'] = to
  if (caps) t['+freeq.at/act-caps'] = caps
  if (deadline !== undefined) t['+freeq.at/act-deadline'] = String(deadline)
  if (ctxHash) t['+freeq.at/act-ctx-h'] = ctxHash
  if (ref) t['+freeq.at/act-ref'] = ref
  return t
}
