import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import nacl from 'tweetnacl'
import { describe, expect, it } from 'vitest'
import { actCanonical, actKid, signAct, verifyAct } from './act'
// the agents' plain-ESM implementation — held to the same vectors so the two
// can never drift apart unnoticed
import { actCanonical as mjsCanonical, actKid as mjsKid, signAct as mjsSign, ulid } from '../../scripts/act.mjs'

// Cross-implementation conformance. These vectors are generated by the RUST
// implementation (freeq-sdk/src/act.rs); reproducing canonical, kid and sigTag
// byte-for-byte is what makes the quest board wire-compatible with real agent
// coordination rather than merely inspired by it.
interface Vector {
  name: string
  seed: string
  publicKey: string
  tags: Record<string, string>
  canonical: string
  kid: string
  sigTag: string
}
const vectors: Vector[] = JSON.parse(
  readFileSync(join(__dirname, '../../fixtures/act-signing-vectors.json'), 'utf8'),
).vectors

const fromHex = (hex: string) => Uint8Array.from(hex.match(/../g)!.map((b) => parseInt(b, 16)))
const b64urlToBytes = (s: string) =>
  Uint8Array.from(Buffer.from(s.replace(/-/g, '+').replace(/_/g, '/'), 'base64'))

describe('freeq.at/act signing — conformance with the Rust implementation', () => {
  for (const v of vectors) {
    describe(v.name, () => {
      const kp = nacl.sign.keyPair.fromSeed(fromHex(v.seed))

      it('derives the same keypair the vector was signed with', () => {
        expect(Buffer.from(kp.publicKey).toString('base64url')).toBe(v.publicKey)
      })

      it('rebuilds the canonical byte-for-byte', () => {
        expect(actCanonical(v.tags)).toBe(v.canonical)
      })

      it('derives the same kid', async () => {
        expect(await actKid(kp.publicKey)).toBe(v.kid)
      })

      it('produces the same signature tag', async () => {
        expect(await signAct(v.tags, kp.secretKey, kp.publicKey)).toBe(v.sigTag)
      })

      it('verifies the vector signature', async () => {
        expect(await verifyAct(v.tags, v.sigTag, kp.publicKey)).toEqual({ ok: true })
      })
    })
  }

  const base = vectors[0]!
  const kp = nacl.sign.keyPair.fromSeed(fromHex(base.seed))

  it('does not cover actor-class, sig, or server tags', () => {
    // the vectors deliberately carry these; adding more must not move the canonical
    const noisy = { ...base.tags, 'msgid': 'different', '+freeq.at/actor-class': 'human', 'time': '2026-01-01T00:00:00Z' }
    expect(actCanonical(noisy)).toBe(base.canonical)
  })

  it('detects a stripped act tag (the tampering the design is built to catch)', async () => {
    const tampered = { ...base.tags }
    delete tampered['+freeq.at/act-caps']
    expect(await verifyAct(tampered, base.sigTag, kp.publicKey)).toEqual({ ok: false, reason: 'sig-invalid' })
  })

  it('detects an altered act value', async () => {
    const tampered = { ...base.tags, '+freeq.at/act-to': 'did:plc:attacker' }
    expect(await verifyAct(tampered, base.sigTag, kp.publicKey)).toEqual({ ok: false, reason: 'sig-invalid' })
  })

  it('distinguishes "wrong key" from "bad signature"', async () => {
    const other = nacl.sign.keyPair.fromSeed(fromHex('03'.repeat(32)))
    expect(await verifyAct(base.tags, base.sigTag, other.publicKey)).toEqual({ ok: false, reason: 'kid-mismatch' })
  })

  it('rejects a malformed sig tag', async () => {
    expect(await verifyAct(base.tags, 'garbage', kp.publicKey)).toEqual({ ok: false, reason: 'malformed' })
  })

  it('accepts unprefixed tag names (a future de-vendoring keeps signatures valid)', () => {
    const unprefixed: Record<string, string> = {}
    for (const [k, val] of Object.entries(base.tags)) unprefixed[k.replace('+freeq.at/', '')] = val
    expect(actCanonical(unprefixed)).toBe(base.canonical)
  })

  // Second implementation, same fixtures. scripts/act.mjs exists because the
  // NPC agents run under bare node; this is what stops it drifting.
  describe('scripts/act.mjs (agent implementation) matches the same vectors', () => {
    for (const v of vectors) {
      it(`${v.name}: canonical, kid and sigTag`, () => {
        const kp = nacl.sign.keyPair.fromSeed(fromHex(v.seed))
        expect(mjsCanonical(v.tags)).toBe(v.canonical)
        expect(mjsKid(kp.publicKey)).toBe(v.kid)
        expect(mjsSign(v.tags, kp.secretKey, kp.publicKey)).toBe(v.sigTag)
      })
    }

    it('agrees with the TypeScript implementation on the canonical', () => {
      for (const v of vectors) expect(mjsCanonical(v.tags)).toBe(actCanonical(v.tags))
    })

    it('mints sortable 26-char ULIDs', () => {
      const a = ulid(1_700_000_000_000)
      const b = ulid(1_700_000_001_000)
      expect(a).toHaveLength(26)
      expect(/^[0-9A-HJKMNP-TV-Z]{26}$/.test(a)).toBe(true)
      expect(a < b).toBe(true) // lexicographic order follows time
    })
  })

  it('the public key in the vector really signs the canonical', () => {
    const sig = base.sigTag.split(':')[2]!
    expect(
      nacl.sign.detached.verify(new TextEncoder().encode(base.canonical), b64urlToBytes(sig), b64urlToBytes(base.publicKey)),
    ).toBe(true)
  })
})
