// `freeq.at/act` — signed, stateful, addressed actions over IRCv3 client tags.
//
// This is the wire format behind the quest board: an offer→claim→complete
// lifecycle that agents and people share. A courier run claimed by a human and
// a work item claimed by a bot are the SAME object on the wire.
//
// Canonical rules are frozen by fixtures/act-signing-vectors.json (generated by
// the Rust implementation in freeq-sdk/src/act.rs). Both implementations must
// reproduce `canonical`, `kid` and `sigTag` byte-for-byte — see act.test.ts.
//
//   - A tag is covered iff its name, with the `+freeq.at/` client-tag prefix
//     stripped, is exactly `act` or starts with `act-`. So `actor-class` and
//     `sig` are NOT covered, and neither are server tags like `msgid`.
//   - Canonical keys are the STRIPPED names: the vendor prefix is wire framing,
//     not semantics, so signatures survive a future de-vendoring.
//   - Values are verbatim strings — `act-deadline` is never coerced to a number.
//   - Canonical bytes are RFC 8785 (JCS) over that string→string map, which for
//     a flat map is JSON with keys sorted by UTF-16 code unit and no whitespace.
//
// Because the signature covers *whatever act-* tags are present* rather than a
// fixed list, adding or stripping one in transit changes the rebuilt canonical
// and the signature fails. Tampering is detected by construction, and new act
// kinds can add fields without a canonical version bump.

import nacl from 'tweetnacl'

export const ACT_SIG_TAG = '+freeq.at/sig'

const CLIENT_TAG_PREFIX = '+freeq.at/'
const TAG_PREFIX = 'freeq.at/'

/** Actions have a lifecycle; these are the `handoff` verbs (RFC v0.4 §Lifecycle). */
export type ActVerb = 'offer' | 'accept' | 'claim' | 'decline' | 'progress' | 'complete' | 'fail' | 'cancel'

export interface ActVerifyResult {
  ok: boolean
  /** why it failed — `kid-mismatch` means "not the key this signature names"
   *  (a lookup problem), `sig-invalid` means the named key was used and the
   *  bytes still don't verify (tampering or forgery). */
  reason?: 'malformed' | 'kid-mismatch' | 'sig-invalid'
}

function strip(name: string): string {
  if (name.startsWith(CLIENT_TAG_PREFIX)) return name.slice(CLIENT_TAG_PREFIX.length)
  if (name.startsWith(TAG_PREFIX)) return name.slice(TAG_PREFIX.length)
  return name
}

/** Covered iff exactly `act` or an `act-` field. Deliberately excludes
 *  `actor-class` (starts with "act" but is not an act field) and `sig`. */
function covered(stripped: string): boolean {
  return stripped === 'act' || stripped.startsWith('act-')
}

function b64url(bytes: Uint8Array): string {
  let s = ''
  for (const b of bytes) s += String.fromCharCode(b)
  const base = typeof btoa === 'function' ? btoa(s) : Buffer.from(bytes).toString('base64')
  return base.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')
}

function b64urlDecode(s: string): Uint8Array {
  const padded = s.replace(/-/g, '+').replace(/_/g, '/')
  const bin = typeof atob === 'function' ? atob(padded) : Buffer.from(padded, 'base64').toString('binary')
  return Uint8Array.from(bin, (c) => c.charCodeAt(0))
}

/**
 * The exact bytes an act signature covers, as a string.
 * JCS over a flat string→string map == JSON, keys sorted by UTF-16 code unit,
 * no insignificant whitespace — which is what `JSON.stringify` emits per key.
 */
export function actCanonical(tags: Record<string, string>): string {
  const fields: Record<string, string> = {}
  for (const [name, value] of Object.entries(tags)) {
    const key = strip(name)
    if (covered(key)) fields[key] = value
  }
  const keys = Object.keys(fields).sort()
  return `{${keys.map((k) => `${JSON.stringify(k)}:${JSON.stringify(fields[k])}`).join(',')}}`
}

/** base64url-nopad(sha256(raw 32-byte ed25519 public key)[0..16]) — self-certifying,
 *  so a looked-up key can be checked against the kid that named it. */
export async function actKid(publicKey: Uint8Array): Promise<string> {
  const digest = await crypto.subtle.digest('SHA-256', publicKey as BufferSource)
  return b64url(new Uint8Array(digest).slice(0, 16))
}

/** Produce the `+freeq.at/sig` value: `ed25519:<kid>:<base64url signature>`. */
export async function signAct(tags: Record<string, string>, secretKey: Uint8Array, publicKey: Uint8Array): Promise<string> {
  const bytes = new TextEncoder().encode(actCanonical(tags))
  const sig = nacl.sign.detached(bytes, secretKey)
  return `ed25519:${await actKid(publicKey)}:${b64url(sig)}`
}

/** Rebuild the canonical from the tags as received and check the signature. */
export async function verifyAct(tags: Record<string, string>, sigTag: string, publicKey: Uint8Array): Promise<ActVerifyResult> {
  const parts = sigTag.split(':')
  if (parts.length !== 3 || parts[0] !== 'ed25519') return { ok: false, reason: 'malformed' }
  const [, kid, sig] = parts as [string, string, string]
  if (kid !== (await actKid(publicKey))) return { ok: false, reason: 'kid-mismatch' }
  let ok = false
  try {
    ok = nacl.sign.detached.verify(new TextEncoder().encode(actCanonical(tags)), b64urlDecode(sig), publicKey)
  } catch {
    return { ok: false, reason: 'malformed' }
  }
  return ok ? { ok: true } : { ok: false, reason: 'sig-invalid' }
}

/** Build the tag set for an action. Omit `to` for an open/claimable action —
 *  unassigned is the natural encoding of unassigned, and the channel it is
 *  posted to is the queue. */
export function actTags(a: {
  kind: string
  verb: ActVerb
  id: string
  from: string
  title?: string
  to?: string
  caps?: string
  deadline?: number
  ctxHash?: string
  ref?: string
}): Record<string, string> {
  const t: Record<string, string> = {
    '+freeq.at/act': a.kind,
    '+freeq.at/act-verb': a.verb,
    '+freeq.at/act-id': a.id,
    '+freeq.at/act-from': a.from,
  }
  if (a.title) t['+freeq.at/act-title'] = a.title
  if (a.to) t['+freeq.at/act-to'] = a.to
  if (a.caps) t['+freeq.at/act-caps'] = a.caps
  if (a.deadline !== undefined) t['+freeq.at/act-deadline'] = String(a.deadline)
  if (a.ctxHash) t['+freeq.at/act-ctx-h'] = a.ctxHash
  if (a.ref) t['+freeq.at/act-ref'] = a.ref
  return t
}
